apiVersion: v1
kind: ConfigMap
metadata:
  name: starbound
data:
  start.sh: |
    #!/bin/bash

    cp -f /config/starbound_server.config /data/storage/

    cd /data/linux/
    exec ./starbound_server

  starbound_server.config: |
    {
      "allowAdminCommands": true,
      "allowAdminCommandsFromAnyone": false,
      "allowAnonymousConnections": true,
      "allowAssetsMismatch": true,
      "anonymousConnectionsAreAdmin": false,
      "bannedIPs": [],
      "bannedUuids": [],
      "checkAssetsDigest": false,
      "clearPlayerFiles": false,
      "clearUniverseFiles": false,
      "clientIPJoinable": false,
      "clientP2PJoinable": true,
      "configurationVersion": {
        "basic": 2,
        "server": 4
      },
      "crafting": {
        "filterHaveMaterials": false
      },
      "gameServerBind": "::",
      "gameServerPort": 21025,
      "interactiveHighlight": true,
      "inventory": {
        "pickupToActionBar": true
      },
      "maxPlayers": 8,
      "maxTeamSize": 4,
      "monochromeLighting": false,
      "playerBackupFileCount": 3,
      "queryServerBind": "::",
      "queryServerPort": 21025,
      "rconServerBind": "::",
      "rconServerPassword": "",
      "rconServerPort": 21026,
      "rconServerTimeout": 1000,
      "runQueryServer": false,
      "runRconServer": false,
      "safeScripts": true,
      "scriptInstructionLimit": 10000000,
      "scriptInstructionMeasureInterval": 10000,
      "scriptProfilingEnabled": false,
      "scriptRecursionLimit": 100,
      "serverFidelity": "automatic",
      "serverName": "A Starbound Server",
      "serverOverrideAssetsDigest": null,
      "serverUsers": {},
      "tutorialMessages": true
    }
